# frozen_string_literal: true

require "json"
require "octokit"
require "uri"

# GitHub API integration for posting PR comments
class GithubIntegration
  COMMENT_IDENTIFIER = "<!-- spm-version-updates-action -->"

  def initialize
    @github_token = ENV.fetch("GITHUB_TOKEN", nil)
    @github_repository = ENV.fetch("GITHUB_REPOSITORY", nil)
    @github_event_path = ENV.fetch("GITHUB_EVENT_PATH", nil)

    if @github_token.nil? || @github_token.empty?
      puts("Warning: GITHUB_TOKEN not set, comments will not be posted")
      @client = nil
      return
    end

    @client = Octokit::Client.new(access_token: @github_token)
    @pr_number = extract_pr_number

    puts("GitHub integration initialized for #{@github_repository}, PR ##{@pr_number}")
  end

  def post_comment(message)
    return unless can_post_comments?

    full_message = build_comment_message(message)

    existing_comment = find_existing_comment
    if existing_comment
      update_comment(existing_comment[:id], full_message)
    else
      create_comment(full_message)
    end
  end

  def post_comment_with_warnings(warnings, warning_details = nil)
    return unless can_post_comments?

    message = build_warnings_message(warnings, warning_details)
    post_comment(message)
  end

  def delete_existing_comment
    return unless can_post_comments?

    existing_comment = find_existing_comment
    return unless existing_comment

    delete_comment(existing_comment[:id])
  end

  private

  def can_post_comments?
    @client && @pr_number
  end

  def extract_pr_number
    return nil unless @github_event_path && File.exist?(@github_event_path)

    event_data = JSON.parse(File.read(@github_event_path))
    event_data.dig("pull_request", "number") || event_data["number"]
  rescue JSON::ParserError => e
    puts("Error parsing GitHub event data: #{e.message}")
    nil
  end

  def build_comment_message(content)
    <<~MARKDOWN
      #{COMMENT_IDENTIFIER}
      ## 📦 SPM Version Updates

      #{content}

      ---
      <sub>Generated by [SPM Version Updates Action](https://github.com/#{@github_repository})</sub>
    MARKDOWN
  end

  def build_warnings_message(warnings, warning_details = nil)
    return "✅ **All SPM dependencies are up to date!**" if warnings.empty?

    details = structured_warning_details(warning_details)
    return build_legacy_warnings_message(warnings) if details.size < warnings.size

    grouped_updates = grouped_warning_details(details)
    package_count = grouped_updates.size
    header = "⚠️ **Found #{package_count} package#{package_count == 1 ? '' : 's'} with potential dependency updates:**\n\n"
    table = grouped_updates
      .map { |group| warning_group_row(group) }
      .join("\n")

    <<~MARKDOWN
      #{header}| Package | Current → Available | Source | Links |
      | --- | --- | --- | --- |
      #{table}

      #{how_to_update_details}
    MARKDOWN
  end

  def build_legacy_warnings_message(warnings)
    header = "⚠️ **Found #{warnings.size} potential dependency update#{warnings.size > 1 ? 's' : ''}:**\n\n"

    # Continuation lines (e.g. "Source: ...") are indented so they stay part
    # of the numbered list item when rendered as Markdown.
    warning_list = warnings.map.with_index(1) { |warning, index|
      "#{index}. #{warning.gsub("\n", "\n   ")}"
    }.join("\n")

    <<~MARKDOWN
      #{header}#{warning_list}

      #{how_to_update_details}
    MARKDOWN
  end

  def how_to_update_details
    <<~MARKDOWN.chomp
      <details>
      <summary>💡 How to update dependencies</summary>

      To update your SPM dependencies:
      - **Package.swift**: bump the version constraint and run `swift package update` (or `swift package resolve`)
      - **Xcode project**: go to **File → Packages → Update to Latest Package Versions**, or update individual packages from the Package Dependencies section in the Project Navigator

      </details>
    MARKDOWN
  end

  def structured_warning_details(warning_details)
    Array(warning_details).select { |detail|
      detail_value(detail, :package) &&
        detail_value(detail, :current_version) &&
        detail_value(detail, :available_version)
    }
  end

  def grouped_warning_details(details)
    details
      .group_by { |detail| detail_value(detail, :normalized_url) || detail_value(detail, :package) }
      .map { |_key, entries| warning_group(entries) }
      .sort_by { |group| group[:package].downcase }
  end

  def warning_group(entries)
    first = entries.first
    sources = entries.filter_map { |detail| detail_value(detail, :source) }
    sources.uniq!

    updates = entries.map { |detail|
      {
        current: detail_value(detail, :current_version),
        available: detail_value(detail, :available_version),
        note: detail_value(detail, :note)
      }
    }
    updates.uniq!

    {
      package: detail_value(first, :package),
      repository_url: detail_value(first, :repository_url),
      sources:,
      updates:
    }
  end

  def warning_group_row(group)
    "| #{table_cell(inline_code(group[:package]))} | #{table_cell(update_cell(group[:updates]))} | " \
      "#{table_cell(source_cell(group[:sources]))} | #{table_cell(links_cell(group))} |"
  end

  def update_cell(updates)
    updates.map { |update|
      summary = "#{inline_code(display_version(update[:current]))} → #{inline_code(display_version(update[:available]))}"
      note = update[:note].to_s.strip
      note.empty? ? summary : "#{summary}<br><sub>#{table_cell(note)}</sub>"
    }.join("<br>")
  end

  def source_cell(sources)
    return "Xcode project" if sources.empty?
    return inline_code(sources.first) if sources.size == 1

    source_list = sources
      .map { |source| inline_code(source) }
      .join("<br>")
    "#{sources.size} manifests<br>#{source_list}"
  end

  def links_cell(group)
    repository = repository_links(group[:repository_url])
    return "N/A" unless repository

    compare_links = group[:updates].map.with_index(1) { |update, index|
      label = group[:updates].size == 1 ? "Compare" : "Compare #{index}"
      "[#{label}](#{compare_url(repository, update[:current], update[:available])})"
    }
    (compare_links + [release_link(repository)]).join("<br>")
  end

  def compare_url(repository, current, available)
    base_url = repository[:base_url]
    current_ref = url_ref(current)
    available_ref = url_ref(available)

    case repository[:host]
    when "github.com"
      "#{base_url}/compare/#{current_ref}...#{available_ref}"
    when "gitlab.com"
      "#{base_url}/-/compare/#{current_ref}...#{available_ref}"
    when "bitbucket.org"
      "#{base_url}/branches/compare/#{current_ref}..#{available_ref}"
    end
  end

  def release_link(repository)
    case repository[:host]
    when "github.com"
      "[Releases](#{repository[:base_url]}/releases)"
    when "gitlab.com"
      "[Releases](#{repository[:base_url]}/-/releases)"
    when "bitbucket.org"
      "[Tags](#{repository[:base_url]}/downloads/?tab=tags)"
    end
  end

  def repository_links(repository_url)
    host, path = repository_host_and_path(repository_url)
    return nil unless host && path

    {
      host:,
      base_url: "https://#{host}/#{path}"
    }
  end

  def repository_host_and_path(repository_url)
    value = repository_url.to_s.strip
    return nil if value.empty?

    match = value.match(%r{\A(?:https?|git|ssh)://(?:[^@/\s]+@)?(?<host>github\.com|gitlab\.com|bitbucket\.org)(?::\d+)?/(?<path>.+)\z}i)
    match ||= value.match(%r{\A(?:[^@/\s]+@)?(?<host>github\.com|gitlab\.com|bitbucket\.org)[:/](?<path>.+)\z}i)
    return nil unless match

    host = match[:host].downcase
    path = repository_path_for(host, match[:path])
    return nil unless path

    [host, path]
  end

  def repository_path_for(host, path)
    segments = normalized_repository_path_segments(path)
    segments = segments.take_while { |segment| segment != "-" } if host == "gitlab.com"

    case host
    when "github.com", "bitbucket.org"
      return nil if segments.size < 2

      segments.first(2).join("/")
    when "gitlab.com"
      return nil if segments.size < 2

      segments.join("/")
    end
  end

  def normalized_repository_path_segments(path)
    path.to_s
      .split(/[?#]/, 2)
      .first
      .to_s
      .sub(%r{\A/+}, "")
      .sub(%r{/+\z}, "")
      .sub(/\.git\z/i, "")
      .split("/")
      .reject(&:empty?)
  end

  def detail_value(detail, key)
    detail[key] || detail[key.to_s]
  end

  def display_version(value)
    text = value.to_s
    text.match?(/\A[0-9a-f]{40}\z/i) ? text[0, 7] : text
  end

  def inline_code(value)
    text = value.to_s
    text.include?("`") ? "``#{text}``" : "`#{text}`"
  end

  def table_cell(value)
    value.to_s.gsub("|", "\\|").gsub("\n", "<br>")
  end

  def url_ref(value)
    URI.encode_www_form_component(value.to_s)
  end

  def find_existing_comment
    return nil unless @pr_number

    comments = @client.issue_comments(@github_repository, @pr_number)
    comments.find { |comment| comment[:body].include?(COMMENT_IDENTIFIER) }
  rescue Octokit::Error => e
    puts("Error fetching existing comments: #{e.message}")
    nil
  end

  def create_comment(message)
    comment = @client.add_comment(@github_repository, @pr_number, message)
    puts("Created new comment: #{comment[:html_url]}")
  rescue Octokit::Error => e
    puts("Error creating comment: #{e.message}")
  end

  def update_comment(comment_id, message)
    comment = @client.update_comment(@github_repository, comment_id, message)
    puts("Updated existing comment: #{comment[:html_url]}")
  rescue Octokit::Error => e
    puts("Error updating comment: #{e.message}")
  end

  def delete_comment(comment_id)
    @client.delete_comment(@github_repository, comment_id)
    puts("Deleted resolved comment: #{comment_id}")
  rescue Octokit::Error => e
    puts("Error deleting comment: #{e.message}")
  end
end
