# frozen_string_literal: true

require "octokit"
require "json"

# GitHub API integration for posting PR comments
class GithubIntegration
  COMMENT_IDENTIFIER = "<!-- spm-version-updates-action -->"

  def initialize
    @github_token = ENV["GITHUB_TOKEN"]
    @github_repository = ENV["GITHUB_REPOSITORY"]
    @github_event_path = ENV["GITHUB_EVENT_PATH"]
    
    if @github_token.nil? || @github_token.empty?
      puts "Warning: GITHUB_TOKEN not set, comments will not be posted"
      @client = nil
      return
    end

    @client = Octokit::Client.new(access_token: @github_token)
    @pr_number = extract_pr_number
    
    puts "GitHub integration initialized for #{@github_repository}, PR ##{@pr_number}"
  end

  def post_comment(message)
    return unless can_post_comments?
    
    full_message = build_comment_message(message)
    
    existing_comment = find_existing_comment
    if existing_comment
      update_comment(existing_comment[:id], full_message)
    else
      create_comment(full_message)
    end
  end

  def post_comment_with_warnings(warnings)
    return unless can_post_comments?
    
    message = build_warnings_message(warnings)
    post_comment(message)
  end

  private

  def can_post_comments?
    @client && @pr_number
  end

  def extract_pr_number
    return nil unless @github_event_path && File.exist?(@github_event_path)
    
    begin
      event_data = JSON.parse(File.read(@github_event_path))
      event_data.dig("pull_request", "number") || event_data["number"]
    rescue JSON::ParserError => e
      puts "Error parsing GitHub event data: #{e.message}"
      nil
    end
  end

  def build_comment_message(content)
    <<~MARKDOWN
      #{COMMENT_IDENTIFIER}
      ## 📦 SPM Version Updates

      #{content}

      ---
      <sub>Generated by [SPM Version Updates Action](https://github.com/#{@github_repository})</sub>
    MARKDOWN
  end

  def build_warnings_message(warnings)
    if warnings.empty?
      "✅ **All SPM dependencies are up to date!**"
    else
      header = "⚠️ **Found #{warnings.size} potential dependency update#{warnings.size > 1 ? 's' : ''}:**\n\n"
      
      warning_list = warnings.map.with_index(1) do |warning, index|
        "#{index}. #{warning}"
      end.join("\n")
      
      <<~MARKDOWN
        #{header}#{warning_list}

        <details>
        <summary>💡 How to update dependencies</summary>

        To update your SPM dependencies:
        1. Open your Xcode project
        2. Go to **File → Swift Packages → Update to Latest Package Versions**
        3. Or update individual packages from the Package Dependencies section in Project Navigator

        </details>
      MARKDOWN
    end
  end

  def find_existing_comment
    return nil unless @pr_number

    begin
      comments = @client.issue_comments(@github_repository, @pr_number)
      comments.find { |comment| comment[:body].include?(COMMENT_IDENTIFIER) }
    rescue Octokit::Error => e
      puts "Error fetching existing comments: #{e.message}"
      nil
    end
  end

  def create_comment(message)
    begin
      comment = @client.add_comment(@github_repository, @pr_number, message)
      puts "Created new comment: #{comment[:html_url]}"
    rescue Octokit::Error => e
      puts "Error creating comment: #{e.message}"
    end
  end

  def update_comment(comment_id, message)
    begin
      comment = @client.update_comment(@github_repository, comment_id, message)
      puts "Updated existing comment: #{comment[:html_url]}"
    rescue Octokit::Error => e
      puts "Error updating comment: #{e.message}"
    end
  end
end